### ISSUE TITLE
Help for error!

### ISSUE THREAD

**Issue by jia-github-pro** [huachao1001/CNNGraph#1]
hello，
      I got  this error when using your code. I really appreciate you can help me with this error. Thank you!
error:
      G[op_name_to_index[inp.op.name]].append(i)
      AttributeError: 'NoneType' object has no attribute 'name'

**Comment by huachao1001** [comment]
具体错误是在第几行代码呢？网络结构有没有什么特殊的OP？

**Comment by jia-github-pro** [comment]
我用的模型是faster_rcnn_inception_v2，错误在utils.py 第10行create_graph里面的，方便加个QQ吗？我的979857007

**Comment by allendred** [comment]
同样的问题
